# Generated by Django 4.0.3 on 2022-08-26 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messsage', models.CharField(max_length=100)),
                ('author', models.ManyToManyField(blank=True, null=True, related_name='userComment', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ManyToManyField(blank=True, null=True, related_name='listingComment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
