# Generated by Django 4.0.3 on 2022-08-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messsage',
            new_name='message',
        ),
    ]
